import { Product } from '@/types/productTypes'; // Adjust the path as necessary

export const products: Product[] = [
  {
    id: 1,
    productUrl: 'templates/estatesphere',
    name: 'EstateSphere',
    price: 70,
    category: 'Website Template',
    createdBy: 'John Doe',
    creationDate: '2024-04-15',
    genre: 'Real Estate',
    noOfPages: 18,
    noOfSections: 30,
    noOfComponents: 45,
    image: '/assets/estate-sphere.png',
    description: `A sleek and modern real estate template designed for property agencies and brokers...`,
    figmaFileIncluded: true,
    componentsUsed: [
      'Dynamic Property Listings',
      'Advanced Search Filter',
      // Other components...
    ],
    otherSpecifications: {
      framework: 'Next.js 13',
      cssFramework: 'Tailwind CSS',
      responsive: true,
      documentationIncluded: true,
      fileFormat: 'Figma, HTML, CSS',
      fileSize: '25MB',
    },
    reviews: [
      { reviewer: 'Alice Smith', rating: 5, comment: 'The best real estate template I’ve used!' },
      // Other reviews...
    ],
  },
  {
    id: 2,
    name: 'SaaSify',
    productUrl: 'templates/saasify',
    price: 80,
    category: 'Website Template',
    createdBy: 'Jane Doe',
    creationDate: '2024-06-01',
    genre: 'SaaS',
    noOfPages: 12,
    noOfSections: 22,
    noOfComponents: 38,
    image: 'https://picsum.photos/800',
    description: `SaaSify is a modern and clean template tailored for SaaS startups...`,
    figmaFileIncluded: true,
    componentsUsed: [
      'Pricing Tables',
      'Testimonial Slider',
      // Other components...
    ],
    otherSpecifications: {
      framework: 'Next.js 13',
      cssFramework: 'Tailwind CSS',
      responsive: true,
      documentationIncluded: true,
      fileFormat: 'Figma, HTML, CSS',
      fileSize: '30MB',
    },
    reviews: [
      { reviewer: 'Chris Martin', rating: 5, comment: 'Perfect for launching my SaaS startup!' },
      // Other reviews...
    ],
  },
  {
    id: 3,
    name: 'PortfolioPro',
    productUrl: 'templates/portfoliopro',
    price: 60,
    category: 'Website Template',
    createdBy: 'Emily Johnson',
    creationDate: '2024-05-10',
    genre: 'Portfolio',
    noOfPages: 10,
    noOfSections: 15,
    noOfComponents: 25,
    image: 'https://picsum.photos/840',
    description: `A stunning portfolio template for creative professionals to showcase their work...`,
    figmaFileIncluded: true,
    componentsUsed: [
      'Project Gallery',
      'About Me Section',
      // Other components...
    ],
    otherSpecifications: {
      framework: 'Next.js 13',
      cssFramework: 'Tailwind CSS',
      responsive: true,
      documentationIncluded: true,
      fileFormat: 'Figma, HTML, CSS',
      fileSize: '20MB',
    },
    reviews: [
      { reviewer: 'Michael Lee', rating: 4, comment: 'Great template, easy to customize!' },
    ],
  },
  {
    id: 4,
    name: 'BlogMaster',
    productUrl: 'templates/blogmaster',
    price: 50,
    category: 'Website Template',
    createdBy: 'Alice Brown',
    creationDate: '2024-06-15',
    genre: 'Blog',
    noOfPages: 8,
    noOfSections: 12,
    noOfComponents: 20,
    image: 'https://picsum.photos/830',
    description: `A clean and minimalist blog template perfect for writers and bloggers...`,
    figmaFileIncluded: true,
    componentsUsed: [
      'Post List',
      'Comments Section',
      // Other components...
    ],
    otherSpecifications: {
      framework: 'Next.js 13',
      cssFramework: 'Tailwind CSS',
      responsive: true,
      documentationIncluded: true,
      fileFormat: 'Figma, HTML, CSS',
      fileSize: '15MB',
    },
    reviews: [
      { reviewer: 'Jessica Green', rating: 5, comment: 'Absolutely love the design!' },
    ],
  },
  {
    id: 5,
    name: 'E-Commerce Hub',
    productUrl: 'templates/ecommercehub',
    price: 90,
    category: 'Website Template',
    createdBy: 'David Wilson',
    creationDate: '2024-07-01',
    genre: 'E-Commerce',
    noOfPages: 20,
    noOfSections: 25,
    noOfComponents: 40,
    image: 'https://picsum.photos/820',
    description: `A comprehensive e-commerce template for online stores and businesses...`,
    figmaFileIncluded: true,
    componentsUsed: [
      'Product Listings',
      'Shopping Cart',
      // Other components...
    ],
    otherSpecifications: {
      framework: 'Next.js 13',
      cssFramework: 'Tailwind CSS',
      responsive: true,
      documentationIncluded: true,
      fileFormat: 'Figma, HTML, CSS',
      fileSize: '35MB',
    },
    reviews: [
      { reviewer: 'Linda Carter', rating: 4, comment: 'Good layout and easy to use!' },
    ],
  },
  {
    id: 6,
    name: 'Eventify',
    productUrl: 'templates/eventify',
    price: 75,
    category: 'Website Template',
    createdBy: 'Mark Thomas',
    creationDate: '2024-07-15',
    genre: 'Event',
    noOfPages: 14,
    noOfSections: 18,
    noOfComponents: 30,
    image: 'https://picsum.photos/850',
    description: `A vibrant template for events and conferences, featuring RSVP functionality...`,
    figmaFileIncluded: true,
    componentsUsed: [
      'Event Schedule',
      'Speaker Profiles',
      // Other components...
    ],
    otherSpecifications: {
      framework: 'Next.js 13',
      cssFramework: 'Tailwind CSS',
      responsive: true,
      documentationIncluded: true,
      fileFormat: 'Figma, HTML, CSS',
      fileSize: '28MB',
    },
    reviews: [
      { reviewer: 'Sarah Parker', rating: 5, comment: 'Perfect for our conference!' },
    ],
  },
  // Add more products as needed...
];
